name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Python (Windows)
      if: runner.os == 'Windows'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        npm install -g pnpm
        npm run install:all

    - name: Build project
      run: npm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Install compression tools
      run: |
        choco install 7zip -y

    - name: List artifacts directory structure
      run: Get-ChildItem -Recurse .\artifacts\ | Format-Table FullName

    - name: Create compressed packages
      run: |
        7z a .\artifacts\dist\vocab_card.zip .\artifacts\dist\win-unpacked\*
        7z a .\artifacts\dist\vocab_card.7z .\artifacts\dist\win-unpacked\*

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .\artifacts\dist\Vocab-review Setup 1.0.0.exe
        asset_name: Vocab-review-Setup-1.0.0.exe
        asset_content_type: application/octet-stream

    - name: Upload Blockmap
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .\artifacts\dist\Vocab-review Setup 1.0.0.exe.blockmap
        asset_name: Vocab-review-Setup-1.0.0.exe.blockmap
        asset_content_type: application/octet-stream

    - name: Upload ZIP Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .\artifacts\dist\vocab_card.zip
        asset_name: vocab_card.zip
        asset_content_type: application/zip

    - name: Upload 7Z Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .\artifacts\dist\vocab_card.7z
        asset_name: vocab_card.7z
        asset_content_type: application/x-7z-compressed